//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAvha.WinForms.MAvhaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        private System.DateTime DOBField;
        
        private int AgeField;
        
        private MAvha.WinForms.MAvhaService.Gender GenderField;
        
        private bool IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public MAvha.WinForms.MAvhaService.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://tempuri.org/")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Femenino = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MAvhaService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        MAvha.WinForms.MAvhaService.ListResponse List(MAvha.WinForms.MAvhaService.ListRequest request);
        
        // CODEGEN: Generating message contract since element name ListJsonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListJson", ReplyAction="*")]
        MAvha.WinForms.MAvhaService.ListJsonResponse ListJson(MAvha.WinForms.MAvhaService.ListJsonRequest request);
        
        // CODEGEN: Generating message contract since element name person from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        MAvha.WinForms.MAvhaService.SaveResponse Save(MAvha.WinForms.MAvhaService.SaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://tempuri.org/", Order=0)]
        public MAvha.WinForms.MAvhaService.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(MAvha.WinForms.MAvhaService.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRequestBody {
        
        public ListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MAvha.WinForms.MAvhaService.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(MAvha.WinForms.MAvhaService.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MAvha.WinForms.MAvhaService.Person[] ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(MAvha.WinForms.MAvhaService.Person[] ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListJson", Namespace="http://tempuri.org/", Order=0)]
        public MAvha.WinForms.MAvhaService.ListJsonRequestBody Body;
        
        public ListJsonRequest() {
        }
        
        public ListJsonRequest(MAvha.WinForms.MAvhaService.ListJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListJsonRequestBody {
        
        public ListJsonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public MAvha.WinForms.MAvhaService.ListJsonResponseBody Body;
        
        public ListJsonResponse() {
        }
        
        public ListJsonResponse(MAvha.WinForms.MAvhaService.ListJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListJsonResult;
        
        public ListJsonResponseBody() {
        }
        
        public ListJsonResponseBody(string ListJsonResult) {
            this.ListJsonResult = ListJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Save", Namespace="http://tempuri.org/", Order=0)]
        public MAvha.WinForms.MAvhaService.SaveRequestBody Body;
        
        public SaveRequest() {
        }
        
        public SaveRequest(MAvha.WinForms.MAvhaService.SaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MAvha.WinForms.MAvhaService.Person person;
        
        public SaveRequestBody() {
        }
        
        public SaveRequestBody(MAvha.WinForms.MAvhaService.Person person) {
            this.person = person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public MAvha.WinForms.MAvhaService.SaveResponseBody Body;
        
        public SaveResponse() {
        }
        
        public SaveResponse(MAvha.WinForms.MAvhaService.SaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveResponseBody {
        
        public SaveResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : MAvha.WinForms.MAvhaService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<MAvha.WinForms.MAvhaService.ServiceSoap>, MAvha.WinForms.MAvhaService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MAvha.WinForms.MAvhaService.ListResponse MAvha.WinForms.MAvhaService.ServiceSoap.List(MAvha.WinForms.MAvhaService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public MAvha.WinForms.MAvhaService.Person[] List() {
            MAvha.WinForms.MAvhaService.ListRequest inValue = new MAvha.WinForms.MAvhaService.ListRequest();
            inValue.Body = new MAvha.WinForms.MAvhaService.ListRequestBody();
            MAvha.WinForms.MAvhaService.ListResponse retVal = ((MAvha.WinForms.MAvhaService.ServiceSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MAvha.WinForms.MAvhaService.ListJsonResponse MAvha.WinForms.MAvhaService.ServiceSoap.ListJson(MAvha.WinForms.MAvhaService.ListJsonRequest request) {
            return base.Channel.ListJson(request);
        }
        
        public string ListJson() {
            MAvha.WinForms.MAvhaService.ListJsonRequest inValue = new MAvha.WinForms.MAvhaService.ListJsonRequest();
            inValue.Body = new MAvha.WinForms.MAvhaService.ListJsonRequestBody();
            MAvha.WinForms.MAvhaService.ListJsonResponse retVal = ((MAvha.WinForms.MAvhaService.ServiceSoap)(this)).ListJson(inValue);
            return retVal.Body.ListJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MAvha.WinForms.MAvhaService.SaveResponse MAvha.WinForms.MAvhaService.ServiceSoap.Save(MAvha.WinForms.MAvhaService.SaveRequest request) {
            return base.Channel.Save(request);
        }
        
        public void Save(MAvha.WinForms.MAvhaService.Person person) {
            MAvha.WinForms.MAvhaService.SaveRequest inValue = new MAvha.WinForms.MAvhaService.SaveRequest();
            inValue.Body = new MAvha.WinForms.MAvhaService.SaveRequestBody();
            inValue.Body.person = person;
            MAvha.WinForms.MAvhaService.SaveResponse retVal = ((MAvha.WinForms.MAvhaService.ServiceSoap)(this)).Save(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
    }
}
